.gitignore, Dockerfile, Makefile, README.md, libprio_wrap.c
This fixes issue #3. This updates the project with some quality-of-life patches.
* A Dockerfile specification for creating a development container
* A patch to the submodule to support `-fPIC`
* Updating the Makefile to automatically build the submodule
This also brings the submodule to the most recent revision.
=> Add a Dockerfile

libprio.i, libprio_wrap.c, prio/lib/prio.py, prio/prio.py, tests/test_client.py, tests/test_lib_client.py
This adds private key import/export added to libprio in mozilla/libprio#51.
This uses the `%rename` and `%ignore` directives to add a custom wrapper around the export functions now that the interface has changed. I rewrote the `MSGPACK_READ` and `MSGPACK_WRITE` macros to do the same thing. 
The PR also changed the casing of some of the argument, which broke some of the tests. The interface file has been changed accordingly.
=> Add private key import/export 

README.md, setup.py
This updates the README to address confusion around #34 due to the submodule. I've also added instructions for building `libprio` in macOS and modified the setup to automatically pull in the appropriate headers and libraries for each supported platform.
=> Update README and setup.py for builds on macOS and Fedora

libprio.i, libprio_wrap.c, prio/libprio.py, setup.py
This updates the libprio submodule to the current HEAD. I've had to modify the swig interface file to include the changes to incompatible `mprio.h` changes that were introduced in [this commit](https://github.com/mozilla/libprio/commit/a95cfdd5eaf7104582709c54ef23395d24d7f7fd).
=> Update the submodule and use `unsigned long long`

README.md
This updates the submodule to remove the linking dependencies. It also updates the status badge to point to the mozilla org.
=> Update submodule for simplified build and status badge

.circleci/config.yml, Dockerfile, libprio.i, libprio_wrap.c, scripts/test-cli-integration
This fixes a bug with the `test-cli-integration` script in Linux by allocating more memory to the msgpack unpacker before reading data into libprio data-structures.
=> Fix memory allocation bug in msgpack reader

.circleci/config.yml
```bash
#!/bin/sh -eo pipefail
echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
if [ "${CIRCLE_BRANCH}" == "master" ]; then
docker tag app:build ${DOCKERHUB_REPO}:latest
docker push ${DOCKERHUB_REPO}:latest
elif  [ ! -z "${CIRCLE_TAG}" ]; then
echo "${DOCKERHUB_REPO}:${CIRCLE_TAG}"
docker tag app:build "${DOCKERHUB_REPO}:${CIRCLE_TAG}"
docker images
docker push "${DOCKERHUB_REPO}:${CIRCLE_TAG}"
fi
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
Error response from daemon: No such image: app:build
Exited with code 1
```
=> Update tag for deploying to dockerhub

.dockerignore, Dockerfile, processor/README.md, processor/prio_processor/__main__.py, processor/prio_processor/bootstrap.py, processor/setup.py, processor/tox.ini
I've added a new command to the `prio-processor` command line tool, which uploads a runner script and the generated egg to a dataproc cluster. 
Here's the testing script -- note that the gcloud dataproc commands do not reference local files at all.
```bash
gcloud dataproc clusters create test-cluster \
--zone us-east1-b \
--image-version 1.4 \
--metadata 'PIP_PACKAGES=click' \
--service-account dataproc-worker@amiyaguchi-dev.iam.gserviceaccount.com \
--initialization-actions \
gs://dataproc-initialization-actions/python/pip-install.sh
docker run \
-e GOOGLE_APPLICATION_CREDENTIALS=/app/.credentials \
-v ~/gcp-service-credentials/amiyaguchi-dev-dbf99a102977.json:/app/.credentials \
-it prio:latest bash -c "cd processor; prio-processor bootstrap --output gs://amiyaguchi-dev/bootstrap/" …
```
=> Add bootstrap script for uploading files for `prio-processor staging`

processor/bin/cleanup, processor/bin/process, processor/setup.py, processor/tests/test_bin_process.py
This will avoid failing if GOOGLE_APPLICATION_CREDENTIALS are not set, and instead assume the roles from the current scope if running inside of google kubernetes engine (GKE).
=> Update authentication for kubernetes engine scopes

processor/bin/process, processor/setup.py
The following error appears:
```
[2019-08-14 22:05:03,982] {logging_mixin.py:95} INFO - [2019-08-14 22:05:03,982] {pod_launcher.py:104} INFO - Running publish
[2019-08-14 22:05:03,990] {logging_mixin.py:95} INFO - [2019-08-14 22:05:03,990] {pod_launcher.py:104} INFO - + jq -c . 'processed/**/*.json'
[2019-08-14 22:05:03,998] {logging_mixin.py:95} INFO - [2019-08-14 22:05:03,998] {pod_launcher.py:104} INFO - jq: error: Could not open file processed/**/*.json: No such file or directory
[2019-08-14 22:05:09,083] {logging_mixin.py:95} INFO - [2019-08-14 22:05:09,083] {pod_launcher.py:121} INFO - Event: run-prio-project-a-15291eba had an event of type Failed
[2019-08-14 22:05:09,084] {logging_mixin.py:95} INFO - [2019-08-14 22:05:09,083] {pod_launcher.py:181} INFO - Event with job id …
```
=> Remove printing of aggregates due to incorrect globbing

prio/cli/commands.py, tests/test_cli.py
Currently the command-line tools will fail if any of the inputs in the current batch do not match with the configuration. This counts the number of bad payloads and continues with the process instead.
```
+ parallel process ::: 'submission_date=2019-08-12/batch_id=content.blocking_blocked-0/part-00000-bc73a2e5-b3b5-4b50-a2a3-f20617e0e656.c000.json
submission_date=2019-08-12/batch_id=content.blocking_blocked_TESTONLY-1/part-00000-bc73a2e5-b3b5-4b50-a2a3-f20617e0e656.c000.json
submission_date=2019-08-12/batch_id=content.blocking_blocked_TESTONLY-0/part-00000-bc73a2e5-b3b5-4b50-a2a3-f20617e0e656.c000.json
submission_date=2019-08-12/batch_id=content.blocking_blocked-1/part-00000-bc73a2e5-b3b5-4b50-a2a3-f20617e0e656.c000.json'
Academic tradition requires you to cite works you base your article …
```
=> Update commands to succeed when inputs are not encoded correctly 

examples/batched-processing/scripts/bootstrap.sh, prio/cli/commands.py, processor/bin/generate, processor/setup.py, tests/test_cli.py
`verify2` and `aggregate` would fail during processing due to a KeyError when joining the original payloads against the outputs of `verify1` or `verify2`. This is based on the way that the commands join the two streams of data, which iterates over all the payloads that were received in the beginning. This simply treats missing data as an error that is logged.
I add a simple test where each of the test partitions is appended with garbage to test robustness. See the following logs for the new output: https://gist.github.com/acmiyaguchi/843dd98c59dd600c96d2dc8db9f00bb5
=> Ignore KeyErrors due to invalid data during joins

Dockerfile, processor/README.md, processor/prio_processor/bootstrap.py, processor/prio_processor/staging.py, processor/tests/test_staging.py, processor/tox.ini
This PR adds read support from BigQuery by using the spark-bigquery connector. This should run as-is on DataProc as before.
As per https://github.com/mozilla/prio-processor/pull/72#issuecomment-525499075, this is tested in the following way. 
```bash
export GOOGLE_APPLICATION_CREDENTIALS=...
docker run \
-v $GOOGLE_APPLICATION_CREDENTIALS:/app/.credentials \
-e GOOGLE_APPLICATION_CREDENTIALS=/app/.credentials \
-it prio:dev bash
cd processor
prio-processor bootstrap --output tmp
gsutil cp gs://spark-lib/bigquery/spark-bigquery-latest.jar tmp/
spark-submit \
--jars tmp/spark-bigquery-latest.jar \
--py-files tmp/prio_processor.egg \
tmp/runner.py \
staging \
--source bigquery \
--date 2019-08-22 \
--input moz-fx-data-shared-prod.payload_bytes_decoded.telemetry_telemetry__prio_v4 \
--output …
```
=> Add BigQuery reads on the Prio payload_decode_bytes table

examples/batched-processing/scripts/check-aggregates.sh, prio/cli/commands.py, processor/README.md, processor/bin/insert, processor/bin/integrate, processor/config/telemetry_origin_data_inc.json, processor/docker-compose.yml, processor/prio_processor/__main__.py, processor/prio_processor/bootstrap.py, processor/prio_processor/cli.py, processor/prio_processor/indexing.py, processor/prio_processor/origins.py, processor/setup.py, processor/tests/test_bin_process.py, processor/tests/test_indexing.py, processor/tests/test_origins.py, tests/test_cli.py
This adds a breaking change to the `prio publish` command by changing the output schema from an array to an object. The `prio-processor fetch-origin` job creates an array that can be zipped with the resulting publish payload to create a tabular json file for insertion into BigQuery.
=> Add script to post-process aggregates

processor/prio_processor/staging.py, processor/tests/test_staging.py
This uses the dynamic partitionOverwriteMode to write new partitions to a dataset without overwriting existing data. I add two tests to ensure that this works as intended, one for testing incremental partitions and another for idempotency.
=> Update staging job for incremental writes

processor/setup.py
This includes a change in #81 that changes the assumption about the format of `BUCKET_*` variables. All buckets must now be prefixed with a protocol.
=> Bump version to 1.6.0

Dockerfile
This fixes #89 by building the prio_processor egg. This was inadvertently removed in #88.
=> Build prio_processor egg

bin/dataproc, prio_processor/spark/commands.py, scripts/test-cli-integration-dataproc, scripts/test-cli-integration-spark, setup.py
I ran the following commands:
```bash
BUCKET=gs://prio-processor-benchmark  N_DATA=32 N_ROWS=2500 MACHINE_TYPE=n1-standard-16 NUM_WORKERS=0 ./scripts/test-cli-integration-dataproc
BUCKET=gs://prio-processor-benchmark  N_DATA=32 N_ROWS=5000 MACHINE_TYPE=n1-standard-16 NUM_WORKERS=0 ./scripts/test-cli-integration-dataproc
BUCKET=gs://prio-processor-benchmark  N_DATA=32 N_ROWS=7500 MACHINE_TYPE=n1-standard-16 NUM_WORKERS=0 ./scripts/test-cli-integration-dataproc
BUCKET=gs://prio-processor-benchmark  N_DATA=32 N_ROWS=10000 MACHINE_TYPE=n1-standard-16 NUM_WORKERS=0 ./scripts/test-cli-integration-dataproc
BUCKET=gs://prio-processor-benchmark  N_DATA=64 N_ROWS=2500 MACHINE_TYPE=n1-standard-16 NUM_WORKERS=0 ./scripts/test-cli-integration-dataproc
BUCKET=gs://prio-processor-benchmark  N_DATA=64 …
```
=> Add dataproc scripts for benchmarking

Dockerfile, requirements-dev.txt, requirements.txt, setup.py
This bumps the dependencies for the container and adds connectors for s3a compatibility. The idea is that s3a will be the only supported connector in the spark job starting in the 4.0 release, which means a bunch of backwards incompatible changes such as requiring hmac keys (e.g. access key and access secret) and using `mc` instead of gsutil. On the other hand, this will make it easier to self-host.
=> Upgrade dependencies, add mc, and jars for s3a connector

bin/process, deployment/testing-v4/LISTING.md, deployment/testing-v4/scripts/list-bucket, docs/guide.md
I was looking through the process script and noticed that the internal intermediate results (the shares meant for the next stage, for the current processor) are being put into a shared bucket. This moves it into the private bucket. The bucket prefixes will remain the same, since it means the two file systems can be overlaid without any name conflicts. 
I also found out about `tree --fromfile` which makes the output from the gsutil listing easier on the eyes. I updated the guide with the current storage convention.
=> Use private bucket for internal intermediate results
